<a href="https://colab.research.google.com/github/fei-ruiz/dune/blob/main/01_richese_conhe/01_Konrad_Lorenz/machine_learning/D4211_04_introduccion_a_pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1. Introducción a Pandas

## ¿Qué es pandas?
Es una librería de análisis de datos que se compone de una serie de estructuras de datos con funcionalidades para limpiar, analizar y preprocesar los datos para tareas siguientes al análisis.

![wget](https://drive.google.com/uc?export=view&id=1mbFgZLmt0qD80FleVEj4cpxh5oO3ocvQ)

## Importando pandas
Pandas se puede importar de la siguiente manera. Se utiliza el nombre pd por facilidad de manejo.

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
pd.__version__

'1.1.5'

## Ejemplos de estructuras de datos

### Series
Una serie es un arreglo unidimensional con un índice correspondiente a cada posición del arreglo. Por ejemplo, el listado de jugadores de un equipo, donde el arreglo tiene los apellidos de los jugadores y el índice el número del jugador.

In [ ]:
seleccionColombia = pd.Series(
    ['Ospina', 'Zapata', 'Falcao', 'Cuadrado', 'Rodriguez'],
    index=[1, 2, 9, 11, 10])

Como se puede observar con los jugadores Cuadrado y Rodriguez, los índices no tienen que estar necesariamente ordenados. La serie se puede imprimir escribiendo su identificador.

In [ ]:
seleccionColombia

1        Ospina
2        Zapata
9        Falcao
11     Cuadrado
10    Rodriguez
dtype: object

Una serie se puede generar sin conocer los índices y Pandas los generará automáticamente con valores desde cero hasta el tamaño de la lista menos uno. En el caso de la misma serie:

In [ ]:
seleccionColombia = pd.Series(
    ['Ospina', 'Zapata', 'Falcao', 'Cuadrado', 'Rodriguez'])
seleccionColombia

0       Ospina
1       Zapata
2       Falcao
3     Cuadrado
4    Rodriguez
dtype: object

### Series desde Diccionarios

Las series tambien pueden ser definidas desde diccionarios:

In [ ]:
dict_selcol = {1:'Ospina', 2: 'Zapata', 9: 'Falcao', 11: 'Cuadrado', 10: 'Rodriguez'}
print(dict_selcol)

{1: 'Ospina', 2: 'Zapata', 9: 'Falcao', 11: 'Cuadrado', 10: 'Rodriguez'}

In [ ]:
ser_selcol = pd.Series(dict_selcol)
ser_selcol.tail()

1        Ospina
2        Zapata
9        Falcao
11     Cuadrado
10    Rodriguez
dtype: object

In [ ]:
whos

Variable            Type      Data/Info
---------------------------------------
dict_selcol         dict      n=5
np                  module    <module 'numpy' from '/us<...>kages/numpy/__init__.py'>
pd                  module    <module 'pandas' from '/u<...>ages/pandas/__init__.py'>
seleccionColombia   Series    0       Ospina\n1       Z<...> Rodriguez\ndtype: object
ser_selcol          Series    1        Ospina\n2       <...> Rodriguez\ndtype: object

### DataFrame
Un DataFrame es una estructura de datos que almacena la información como una tabla ordenada por filas y columnas. Cada fila representa un objeto y cada columna la información correspondiente a una característica de los objetos.

Un DataFrame también posee índices por cada fila, que pueden ser dados o generados automáticamente. Cada columna del DataFrame es una serie, donde el valor del índice corresponde con los valores de índice que tiene el DataFrame.

Por medio de un diccionario vamos a crear un dataframe, donde las llaves son los nombres de las columnas y los valores son la lista de valores que tienen las características.

Por ejemplo, para hacer un DataFrame con el equipo de fútbol anterior, pero agregando estatura y peso, podemos hacerlo de la siguiente manera:

In [ ]:
# a partir de un diccionario
dict_caracteristicas = {'apellido':['Ospina', 'Zapata', 'Falcao', 'Cuadrado', 'Rodriguez'],
                       'altura':[183.0,187.0,177.0,179.0,180.0],
                       'peso':[80.0,82.0,72.0,72.0,75.0]}

seleccionColombia = pd.DataFrame(dict_caracteristicas,index=[1, 2, 9, 11, 10])
print(seleccionColombia)

     apellido  altura  peso
1      Ospina   183.0  80.0
2      Zapata   187.0  82.0
9      Falcao   177.0  72.0
11   Cuadrado   179.0  72.0
10  Rodriguez   180.0  75.0

Al imprimir el DataFrame, podemos observar que su estructura es similar a la de un documento en Excel, donde el índice (que no tiene nombre de columna) es el número del jugador.

In [ ]:
seleccionColombia

     apellido  altura  peso
1      Ospina   183.0  80.0
2      Zapata   187.0  82.0
9      Falcao   177.0  72.0
11   Cuadrado   179.0  72.0
10  Rodriguez   180.0  75.0

## Acceso a los registros del DataFrame por el índice

En pandas podemos acceder a la fila por el índice de ésta. En el ejemplo anterior éste índice era el número de la camiseta del jugador. Pero podría ser una fecha, una letra, etc.

Si conocemos el índice simplemente lo usamos para ir directamente a la fila deseada.

In [ ]:
seleccionColombia.loc[1]

apellido    Ospina
altura         183
peso            80
Name: 1, dtype: object

Para agregar un nuevo jugador, se puede utilizar el índice, que en este caso es el número en el equipo y un arreglo representando todas sus características (apellido, altura y peso).

NOTA: Las características tienen que estar en el mismo orden.

In [ ]:
num_jugador = 3
caract_jugador = ['Murillo',184,82.0]
seleccionColombia.loc[num_jugador] = caract_jugador

Imprimiendo el DataFrame podemos ver el nuevo jugador.

In [ ]:
seleccionColombia

     apellido  altura  peso
1      Ospina   183.0  80.0
2      Zapata   187.0  82.0
9      Falcao   177.0  72.0
11   Cuadrado   179.0  72.0
10  Rodriguez   180.0  75.0
3     Murillo   184.0  82.0

## Borrar Columna o Fila

In [ ]:
seleccionColombia.keys()

Index(['apellido', 'altura', 'peso'], dtype='object')

In [ ]:
seleccionColombia.drop?

In [ ]:
seleccionColombia.drop('peso',axis=1, inplace=False) # Para que sea *permanente* inplace=True

     apellido  altura
1      Ospina   183.0
2      Zapata   187.0
9      Falcao   177.0
11   Cuadrado   179.0
10  Rodriguez   180.0
3     Murillo   184.0

In [ ]:
seleccionColombia

     apellido  altura  peso
1      Ospina   183.0  80.0
2      Zapata   187.0  82.0
9      Falcao   177.0  72.0
11   Cuadrado   179.0  72.0
10  Rodriguez   180.0  75.0
3     Murillo   184.0  82.0

Si queremos eliminar una columna permanentemente también se puede usar:

In [ ]:
#del seleccionColombia['peso']

In [ ]:
seleccionColombia

     apellido  altura  peso
1      Ospina   183.0  80.0
2      Zapata   187.0  82.0
9      Falcao   177.0  72.0
11   Cuadrado   179.0  72.0
10  Rodriguez   180.0  75.0
3     Murillo   184.0  82.0

Si queremos saber cuales son las columnas actuales del data frame, usamos la propiedad 'columns' del objeto.

In [ ]:
seleccionColombia.columns

Index(['apellido', 'altura', 'peso'], dtype='object')

Si queremos conocer el indice del dataframe, con lo propiedad 'index' la conocemos.

In [ ]:
seleccionColombia.index

Int64Index([1, 2, 9, 11, 10, 3], dtype='int64')

Para ordenar el dataframe se usa la función sort.

In [ ]:
seleccionColombia.sort_values?

In [ ]:
seleccionColombia.sort_values(by=['altura','peso'],ascending=False) #inplace=False por defecto

     apellido  altura  peso
2      Zapata   187.0  82.0
3     Murillo   184.0  82.0
1      Ospina   183.0  80.0
10  Rodriguez   180.0  75.0
11   Cuadrado   179.0  72.0
9      Falcao   177.0  72.0

## Datos faltantes: rellenar valores NaN con algo más

En algunas ocaciones vamos a tener valores inválidos en nuestros dataframes. Estos valores son un problema al momento de hacer cálculos numéricos o tomar estadísticas.

Para esto es necesario dejar fuera del dataframe estos campos.

En las siguientes líneas usted verá cómo se eliminan estos valores.

In [ ]:
import numpy as np

In [ ]:
df = pd.DataFrame({'col1':[1,2,3,np.nan],
                   'col2':[np.nan,555,666,444],
                   'col3':['abc','def','ghi','xyz']})
df.head()

   col1   col2 col3
0   1.0    NaN  abc
1   2.0  555.0  def
2   3.0  666.0  ghi
3   NaN  444.0  xyz

In [ ]:
df['col1'].mean()

2.0

**Hallar valores NULL o verificarlos**

In [ ]:
df.isnull()
np.sum(df.isnull()*1)

col1    1
col2    1
col3    0
dtype: int64

Encontrar y reemplazar, quiero reemplzar los nulos (nan) por elvalor que yo quiera

In [ ]:
df.fillna(0, inplace=True) # inplace=False por defecto

In [ ]:
df

   col1   col2 col3
0   1.0    0.0  abc
1   2.0  555.0  def
2   3.0  666.0  ghi
3   0.0  444.0  xyz

In [ ]:
# Eliminar filas con valores NaN
df.dropna()

   col1   col2 col3
0   1.0    0.0  abc
1   2.0  555.0  def
2   3.0  666.0  ghi
3   0.0  444.0  xyz

## Quiz

Complete la  función `pair_odds` la cual  recibe un número entero `n` y debe retornar un dataframe  con las siguientes columnas  `['pares','impares']` con el contenido de los primeros `n` números pares -empezado en 2- y en la columna impares los primeros `n` impares -empezando en 1-.

Por ejemplo si `n` es igual a 3, pares=2,4,6, impares=1,3,5.

In [ ]:
def pair_odds(n):
  """
  Parámetros:
     n: número de elementos para calcular los pares e impares

  Retorna:
     df_res: dataframe con las columnas 'pares','impares' para almacenar los valores calculados
  """
  df_nums = pd.DataFrame(columns = ['pares','impares'])
  #Ponga su código acá
  for x in range(n):
    df_nums.loc[(x+1)] = [2*(x+1), 2*(x+1)-1]

  return df_nums


def test_pair_odds(n):
  try:
    res = pair_odds(n)
  except:
    raise Exception("Error en la función")
  #Validar la respuesta
  _is_ok = np.sum((res['pares']-res['impares']))==n
  if not _is_ok:
    raise Exception("Error en el cálculo de los pares e impares")
  return True

In [ ]:
# No correr esta línea, es solo para comparar su respuesta
pair_odds(15)

   pares impares
1      2       1
2      4       3
3      6       5
4      8       7
5     10       9
6     12      11
7     14      13
8     16      15
9     18      17
10    20      19
11    22      21
12    24      23
13    26      25
14    28      27
15    30      29

In [ ]:
df_nums = test_pair_odds(10)
df_nums

True

# 2. Acceso a datos

## Carga y Guardado de Datos

Pandas permite leer archivos en diferentes formatos, como txt, csv y excel. En este ejemplo se leerá un dataset correspondiente a la información nutricional de un listado de 80 cereales. El dataset puede ser descargado en el siguiente enlace (botón Downloads):

https://www.kaggle.com/crawford/80-cereals

Como el formato es .csv, se lee usando la función de pandas read_csv usando como parámetro la dirección del archivo. Si el archivo está en la misma carpeta del notebook, se puede usar solo su nombre.

In [ ]:
!gdown --id 17c7H-D3zpLthS0LJYCnN5DCHx0_iLZh8
#https://drive.google.com/file/d/1tvoXwREylDcwUQShWDMhkMZKNNZBH8KW/view?usp=sharing
!gdown2 --id 1tvoXwREylDcwUQShWDMhkMZKNNZBH8KW

Downloading...
From: https://drive.google.com/uc?id=17c7H-D3zpLthS0LJYCnN5DCHx0_iLZh8
To: /content/cereal.csv
100% 5.06k/5.06k [00:00<00:00, 4.35MB/s]
/bin/bash: gdown2: command not found

In [ ]:
from google.colab import drive
drive.mount('/content/gdrive')
df_cereal = pd.read_csv('/content/gdrive/MyDrive/4. Postgrado/2do Semestre (2H2021)/D4211 Machine Learning/cereal.csv')

Mounted at /content/gdrive

In [ ]:
#head(df_cereals)
df_cereal.head()

                        name mfr type  calories  ...  shelf  weight  cups     rating
0                  100% Bran   N    C        70  ...      3     1.0  0.33  68.402973
1          100% Natural Bran   Q    C       120  ...      3     1.0  1.00  33.983679
2                   All-Bran   K    C        70  ...      3     1.0  0.33  59.425505
3  All-Bran with Extra Fiber   K    C        50  ...      3     1.0  0.50  93.704912
4             Almond Delight   R    C       110  ...      3     1.0  0.75  34.384843

[5 rows x 16 columns]

In [ ]:
url="https://drive.google.com/uc?id=17c7H-D3zpLthS0LJYCnN5DCHx0_iLZh8"
df_cereals = pd.read_csv(url)

In [ ]:
df_cereals

NameError: ignored

In [ ]:
cereals = pd.read_csv("cereal.csv")
cereals

Si quiere conocer más formatos de entrada/salida como json, excel, hdf5, SQL, etc. Puede ir a la siguiente URL:

https://pandas.pydata.org/pandas-docs/stable/io.html

### Funciones para revisión de los datos
Lo primero que haremos es revisar las propiedades que tienen las columnas del DataFrame. Como el nombre de las columnas y sus tipos:

In [ ]:
print("Columnas: ",df_cereal.columns.tolist())

Columnas:  ['name', 'mfr', 'type', 'calories', 'protein', 'fat', 'sodium', 'fiber', 'carbo', 'sugars', 'potass', 'vitamins', 'shelf', 'weight', 'cups', 'rating']

La función Info nos da un resumen del DataFrame y sus datos.

In [ ]:
df_cereal.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 77 entries, 0 to 76
Data columns (total 16 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   name      77 non-null     object
 1   mfr       77 non-null     object
 2   type      77 non-null     object
 3   calories  77 non-null     int64
 4   protein   77 non-null     int64
 5   fat       77 non-null     int64
 6   sodium    77 non-null     int64
 7   fiber     77 non-null     float64
 8   carbo     77 non-null     float64
 9   sugars    77 non-null     int64
 10  potass    77 non-null     int64
 11  vitamins  77 non-null     int64
 12  shelf     77 non-null     int64
 13  weight    77 non-null     float64
 14  cups      77 non-null     float64
 15  rating    77 non-null     float64
dtypes: float64(5), int64(8), object(3)
memory usage: 9.8+ KB

La función dtypes sólo nos indica los tipo de datos de las columnas.

In [ ]:
whos

Variable               Type         Data/Info
---------------------------------------------
caract_jugador         list         n=3
df                     DataFrame       col1   col2 col3\n0   <...> ghi\n3   0.0  444.0  xyz
df_cereal              DataFrame                             <...>n\n[77 rows x 16 columns]
df_nums                bool         True
dict_caracteristicas   dict         n=3
dict_selcol            dict         n=5
drive                  module       <module 'google.colab.dri<...>s/google/colab/drive.py'>
np                     module       <module 'numpy' from '/us<...>kages/numpy/__init__.py'>
num_jugador            int          3
pair_odds              function     <function pair_odds at 0x7f1ca269f4d0>
pd                     module       <module 'pandas' from '/u<...>ages/pandas/__init__.py'>
seleccionColombia      DataFrame         apellido  altura  pe<...>    Murillo   184.0  82.0
ser_selcol             Series       1        Ospina\n2       <...> Rodriguez\ndtype: object
test_pair_odds         function     <function test_pair_odds at 0x7f1ca269f200>

In [ ]:
df_cereal.dtypes

name         object
mfr          object
type         object
calories      int64
protein       int64
fat           int64
sodium        int64
fiber       float64
carbo       float64
sugars        int64
potass        int64
vitamins      int64
shelf         int64
weight      float64
cups        float64
rating      float64
dtype: object

Se puede observar que Pandas es capaz de inferir el tipo de columna a partir de los datos.

Para darle un vistazo inicial al DataFrame se puede utilizar la función head del DataFrame, que tiene como parámetro el número de filas que queremos observar, comenzando en orden por la primera.

In [ ]:
df_cereal.tail(3)

                   name mfr type  calories  ...  shelf  weight  cups     rating
74           Wheat Chex   R    C       100  ...      1     1.0  0.67  49.787445
75             Wheaties   G    C       100  ...      1     1.0  1.00  51.592193
76  Wheaties Honey Gold   G    C       110  ...      1     1.0  0.75  36.187559

[3 rows x 16 columns]

La función describe nos entrega las estadísticas descriptivas que nos permite conocer la tendencia de los datos, dispersión, distribución, valores nulos y otros más.

In [ ]:
df_cereal.describe()

         calories    protein        fat  ...     weight       cups     rating
count   77.000000  77.000000  77.000000  ...  77.000000  77.000000  77.000000
mean   106.883117   2.545455   1.012987  ...   1.029610   0.821039  42.665705
std     19.484119   1.094790   1.006473  ...   0.150477   0.232716  14.047289
min     50.000000   1.000000   0.000000  ...   0.500000   0.250000  18.042851
25%    100.000000   2.000000   0.000000  ...   1.000000   0.670000  33.174094
50%    110.000000   3.000000   1.000000  ...   1.000000   0.750000  40.400208
75%    110.000000   3.000000   2.000000  ...   1.000000   1.000000  50.828392
max    160.000000   6.000000   5.000000  ...   1.500000   1.500000  93.704912

[8 rows x 13 columns]

Para una descripción rápida se puede utilizar la función describe.

## Indexación
En Pandas la indexación es similar a la que se tiene en Numpy. El resultado de obtener resultados por indexación es otro DataFrame correspondiente a ciertas filas del DataFrame original.

### Obtención de filas por índice
Un ejemplo es acceder a una fila por medio de la función iloc. En la siguiente celda se selecciona el cereal con índice 7.

In [ ]:
info_cereal_7 = df_cereal.iloc[7]
info_cereal_7

name        Basic 4
mfr               G
type              C
calories        130
protein           3
fat               2
sodium          210
fiber             2
carbo            18
sugars            8
potass          100
vitamins         25
shelf             3
weight         1.33
cups           0.75
rating      37.0386
Name: 7, dtype: object

### Obtención de valores por columna
Para obtener toda la información de una columna, se puede acceder al DataFrame como un diccionario, en donde la llave es la columna a la que queremos acceder.

In [ ]:
info_calories = df_cereal['sodium']

Veamos que si usamos el acceso con un corchete cuadrado, nos retorna un objeto tipo series.

In [ ]:
type(info_calories)

pandas.core.series.Series

En cambio si usamos doble corchete, nos retorna un dataframe con la columna.

In [ ]:
type(df_cereal[['sodium']])

pandas.core.frame.DataFrame

La información de columna se obtiene en el mismo orden que en el DataFrame original. Al imprimirlo, podemos ver en la primera columna el valor del índice y en la segunda el valor de la columna seleccionada.

In [ ]:
print(info_calories[10:15])

10    220
11    290
12    210
13    140
14    180
Name: sodium, dtype: int64

Se pueden seleccionar más de una columna del DataFrame a la vez.

In [ ]:
info_sodium_carbon = df_cereal[['sodium','carbo']]

In [ ]:
info_sodium_carbon[0:5]

   sodium  carbo
0     130    5.0
1      15    8.0
2     260    7.0
3     140    8.0
4     200   14.0

### Obtención de valores usando condiciones
Con Pandas, se pueden seleccionar columnas cuyas características cumplan ciertas condiciones. Por ejemplo, los cereales con menos de 100 calorias. Para ello se hace la selección de la columna, se evalua la condición con esta y luego se selecciona del DataFrame el segmento que cumple la condición de la siguiente manera:

In [ ]:
df_cereal['sodium'] <= 130

0      True
1      True
2     False
3     False
4     False
      ...
72    False
73    False
74    False
75    False
76    False
Name: sodium, Length: 77, dtype: bool

In [ ]:
#Seleccion de columna: df_cereals['calories']
#Condicion sobre esa columna: df_cereals['calories'] < 100
#Seleccion de fragmento de dataframe que cumple la condicion:
    #df_cereals[df_cereals['calories'] < 100]
less_130_sod = df_cereal[ df_cereal['sodium'] < 130 ]

In [ ]:
less_130_sod

Las condiciones se pueden mezclar usando operadores lógicos, por ejemplo cereales con menos de 100 calorias y sin grasa (valor 0 en fat).

In [ ]:
condition_sodium = df_cereal['sodium'] <= 170
condition_sodium1 = df_cereal['sodium'] >= 130
btwn_cereal = df_cereal[condition_sodium & condition_sodium1]
btwn_cereal

In [ ]:
condition_sodium = df_cereal['sodium'] <= 170
condition_sodium1 = df_cereal['sodium'] >= 130
btwn_cereal = df_cereal[condition_sodium & condition_sodium1]
btwn_cereal

In [ ]:
less_100_cal_and_fat.describe()

Teniendo en cuenta que el resultado de la indexación también es un DataFrame, se pueden hacer operaciones similares sobre el resultado, que en este caso tiene el identificador less_100_cal_and_fat.

In [ ]:
less_100_cal_and_fat.head(5)

### Ejemplos de operaciones sobre DataFrames

Como se vio al usar la función describe, con el DataFrame se pueden hacer operaciones matemáticas, como hallar la media y desviación estándar. En este caso vamos a hallar la media de calificaciones de los cereales que tienen menos de 100 calorias y no tienen grasa. Al ser el rating una columna, la operación de media se calcula sobre esta columna.

In [ ]:
less_100_cal_and_fat

In [ ]:
less_100_cal_and_fat['shelf'].mean()

La desviación estándar sobre el rating se puede calcular de la siguiente manera.

In [ ]:
less_100_cal_and_fat['shelf'].std()

El máximo rating también se puede calcular.

In [ ]:
max_rate = less_100_cal_and_fat['shelf'].max()
max_rate

Usando el máximo podemos mirar cual es el nombre del cereal con menos de 100 calorias y sin grasa.

In [ ]:
condition_max_rating = less_100_cal_and_fat['shelf'] == max_rate
best_cereal_less_100_no_fat = less_100_cal_and_fat[condition_max_rating]

In [ ]:
best_cereal_less_100_no_fat

In [ ]:
best_cereal_less_100_no_fat['name']

#Taller
Cargar datos a un dataframe provenientes de un archivo serparado por comas (CSV) y realicen las siguientes operaciones:

*   Obtengan la descripción de los datos (describe)
*   Crear 1 filtro simple y 1 filtro compuesto sobre columnas

### Multi-Indices

Los dataframes pueden tener varios índices usando la funcionalidad de MultiIndex. Estos se pueden crear a partir de una lista de tuplas, con el método from_tuples, donde cada tupla contiene los nombres de cada columna o a partir de una combinación entre varias tuplas con el método from_product

In [ ]:
columnas = pd.MultiIndex.from_tuples([('A', 'positivo'), ('B', 'positivo'),
                                     ('A', 'negativo'), ('B', 'negativo'),
                                     ('O', 'positivo')],
                                     names=['tipo', 'Rh'])

Ahora se crea el Indice

In [ ]:
filas = pd.MultiIndex.from_product([('menor', 'adulto'),('hombre', 'mujer')],
                                   names=['edad', 'sexo'])

df = pd.DataFrame(np.random.randn(4,5), columns=columnas, index=filas)
df

Para obtener información de las columnas de otros niveles, se debe referir primero la columna de primer nivel y luego a las de los niveles siguientes, en órden jerárquico.

In [ ]:
df['B', 'positivo']

La función xs retorna la sección transversal de un DataFrame que usa multi-índices.
Por ejemplo, es útil cuando queremos filtrar todos los elementos de un determinado "Num" en el DataFrame anterior, independientemente de su Grupo.

In [ ]:
# En este caso seleccionamos el Num=1
df.xs('hombre',level='sexo')

## Quiz

Tomando como base el siguiente arreglo de numpy, cree un dataframe con las columnas X, Y.

Y efectúe las siguientes operaciones.

a) Hallar la media de X y de  Y.

b) Hallar la deviación stándar de X y de Y .


Modifique la función calculate_stats para hallar los estadísticos requeridos.

In [ ]:
def calculate_stats(df_x_y):
  """
  Parámetros:
     df_x_y: dataframe con la columna X y Y

  Retorna:
    mean_x, std_x, mean_y, std_y: valores con la media y desviación estándar
    de 'x' y 'y' respectivamente
  """
  mean_x, std_x, mean_y, std_y = 0, 0, 0, 0

  #COLOQUE AQUI SU CÓDIGO

  return mean_x, std_x, mean_y, std_y

In [ ]:
df = pd.DataFrame({'X':[4,8,3,44,6],
                   'Y':[6,2,376,72,5]})
df.head()

In [ ]:
# NO CORRA ESTA CELDA, AQUI COMPRUEBA SU CÓDIGO

calculate_stats(best_cereal_less_100_no_fat[["protein","sugars"]])

In [ ]:
#PRUEBE AQUI SU CÓDIGO
calculate_stats(df)

In [ ]:
#PRUEBE AQUI SU CÓDIGO
test_calculate_stats(df)

# 3. Manipulando Data Frames

## Combinando DataFrames

Hay 3 maneras de combinar DataFrames:
Concatenar (concat)
Fusionar (merge)
Unir (join)

![wget](https://drive.google.com/uc?export=view&id=1wmJo-FJnofniKEkF-3RRR-Mk9IVuc-Nx)

_____
** DataFrames de ejemplo **

In [ ]:
df1 = pd.DataFrame({'A': ['A0', 'A1', 'A2', 'A3'],
                        'B': ['B0', 'B1', 'B2', 'B3'],
                        'C': ['C0', 'C1', 'C2', 'C3'],
                        'D': ['D0', 'D1', 'D2', 'D3']},
                        index=[0, 1, 2, 3])

In [ ]:
df2 = pd.DataFrame({'A': ['A4', 'A5', 'A6', 'A7'],
                        'B': ['B4', 'B5', 'B6', 'B7'],
                        'C': ['C4', 'C5', 'C6', 'C7'],
                        'D': ['D4', 'D5', 'D6', 'D7']},
                         index=[4, 5, 6, 7])

In [ ]:
df3 = pd.DataFrame({'A': ['A8', 'A9', 'A10', 'A11'],
                        'B': ['B8', 'B9', 'B10', 'B11'],
                        'C': ['C8', 'C9', 'C10', 'C11'],
                        'D': ['D8', 'D9', 'D10', 'D11']},
                        index=[8, 9, 10, 11])

In [ ]:
df1

In [ ]:
df2

In [ ]:
df3

### Concatenar (concat)

La concatenación básicamente pega DataFrames, uno después de otro. Hay que tener en cuenta que las dimensiones deben coincidir a lo largo del eje con el que se está concatenando.

Puede usar **pd.concat** y pasar una lista de DataFrames para concatenarlos:

In [ ]:
pd.concat([df1,df2,df3])

In [ ]:
pd.concat([df1,df2,df3],axis=1)    # axis=1 concatena a lo largo de las columnas, llenando las celdas desconocidas con NaN

___

### Fusionar (merge)

La función **merge** permite fusionar DataFrames utilizando una lógica similar a la combinación de Tablas SQL. Por ejemplo:

In [ ]:
izq = pd.DataFrame({'key': ['K0', 'K1', 'K2', 'K3'],
                     'A': ['A0', 'A1', 'A2', 'A3'],
                     'B': ['B0', 'B1', 'B2', 'B3']})

der = pd.DataFrame({'key': ['K0', 'K1', 'K2', 'K3'],
                          'C': ['C0', 'C1', 'C2', 'C3'],
                          'D': ['D0', 'D1', 'D2', 'D3']})

In [ ]:
izq

In [ ]:
der

In [ ]:
pd.merge(izq, der, on='key')

Otro ejemplo más completo:

In [ ]:
izq = pd.DataFrame({'key1': ['K0', 'K0', 'K1', 'K2'],
                     'key2': ['K0', 'K1', 'K0', 'K1'],
                        'A': ['A0', 'A1', 'A2', 'A3'],
                        'B': ['B0', 'B1', 'B2', 'B3']})

der = pd.DataFrame({'key1': ['K0', 'K1', 'K1', 'K2'],
                               'key2': ['K0', 'K0', 'K0', 'K0'],
                                  'C': ['C0', 'C1', 'C2', 'C3'],
                                  'D': ['D0', 'D1', 'D2', 'D3']})

In [ ]:
izq

In [ ]:
der

In [ ]:
pd.merge(izq, der, on=['key1', 'key2'])

#### Argumento 'how'

El método merge recibe el argumento 'how'. Éste especifica cómo determinar qué claves se incluirán en la tabla resultante. Si una combinación de dichas llaves no aparece en las tablas izquierda o derecha, los valores en la tabla fusionada serán NaN.

Aquí hay un resumen de las opciones de 'how' y sus nombres equivalentes en SQL:

	PANDAS	SQL					DESCRIPCIÓN
	inner	INNER JOIN			Usa la intersection de las llaves de ambos dataframes * Por defecto
    left	LEFT OUTER JOIN		Sólo usa las llaves del dataframe izquierdo
	right	RIGHT OUTER JOIN	Sólo usa las llaves del dataframe derecho
	outer	FULL OUTER JOIN		Usa la unión de las llaves de ambos dataframes

![](https://drive.google.com/uc?export=view&id=1k9cAel1FLYgou8ITAeqKE3vOIFBJydQB)

In [ ]:
pd.merge(izq, der, how='outer', on=['key1', 'key2'])

In [ ]:
pd.merge(izq, der, how='left', on=['key1', 'key2'])

In [ ]:
pd.merge(izq, der, how='right', on=['key1', 'key2'])

In [ ]:
pd.merge(izq, der, how='right', on=['key1', 'key2'])

### Unión (join)

El join es un método para combinar las columnas de dos DataFrames indexados de forma diferente en un solo DataFrame de resultados.

En vez de columnas como en el merge, en el join se utilizan los índices de los DataFrames para hacer la combinación.

In [ ]:
izq = pd.DataFrame({'A': ['A0', 'A1', 'A2'],
                     'B': ['B0', 'B1', 'B2']},
                      index=['K0', 'K1', 'K2'])

der = pd.DataFrame({'C': ['C0', 'C2', 'C3'],
                    'D': ['D0', 'D2', 'D3']},
                      index=['K0', 'K2', 'K3'])

In [ ]:
izq

In [ ]:
der

In [ ]:
izq.join(der)

In [ ]:
der.join(izq)

In [ ]:
izq.join(der, how='outer')

In [ ]:
izq.join(der, how='inner')

## Función Apply

In [ ]:
df = pd.DataFrame(np.random.randn(4,5), columns=columns, index=index)
df

In [ ]:
df['A'].sum()

In [ ]:
def times2(x):
    return x*2

In [ ]:
df['A']

In [ ]:
df['A'].apply(times2)

In [ ]:
df['B']

In [ ]:
# Apply es muy útil y puede ser usado también con expresiones lambda

df['B'].apply(lambda x: x*0.19)

In [ ]:
# También se puede usar con funciones predeterminadas como len
df['B'].apply(lambda x: x*2)

## Tablas Pivote

In [ ]:
data = {'A':['foo','foo','foo','bar','bar','bar'],
     'B':['uno','uno','dos','dos','uno','uno'],
       'C':['categoria 1','categoria 1','categoria 1','categoria 2','categoria 1','categoria 2'],
       'D':[5,3,2,5,4,1]}

df = pd.DataFrame(data)

In [ ]:
df

In [ ]:
df.pivot_table(values='D',index=['A', 'B'],columns=['C'])

In [ ]:
df.pivot_table?

Otro ejemplo:

In [ ]:
df = pd.DataFrame({"A": ["foo", "foo", "foo", "foo", "foo",
                         "bar", "bar", "bar", "bar"],
                    "B": ["one", "one", "one", "two", "two",
                          "one", "one", "two", "two"],
                    "C": ["small", "large", "large", "small",
                          "small", "large", "small", "small",
                          "large"],
                    "D": [1, 2, 2, 3, 3, 4, 5, 6, 7]})
df

In [ ]:
table = df.pivot_table(values='D', index=['A', 'B'],
                     columns=['C'], aggfunc=np.sum)
table

In [ ]:
otro =df.stack()

## Agrupaciones y agregaciones: Groupby

El método groupby permite agrupar filas de datos basándose en el valor de una columna, y llamar a funciones de agregación sobre los datos: suma, conteo, promedio, ...

![](https://drive.google.com/uc?export=view&id=1dxdpTG6ZJovzaxzerMFLPIv8daDlfFvV)

In [ ]:
import pandas as pd

# Datos para crear el dataframe
data = {'Empresa':['GOOG','GOOG','MSFT','MSFT','FB','FB'],
       'Persona':['Ana','Carlos','Manuela','Vanessa','Camilo','Sara'],
       'Ventas':[200,120,340,124,243,350]}

In [ ]:
df = pd.DataFrame(data)

In [ ]:
df

**Ahora usaremos el método .groupby() para agrupar las filas basándose en los datos de una columna. Por ejemplo, el nombre de la compañía. Esto creará un objeto DataFrameGroupBy.**

In [ ]:
df.groupby('Empresa')

Se puede guardar este objeto como una nueva variable:

In [ ]:
by_empresa = df.groupby("Empresa")
by_empresa

In [ ]:
df.groupby?

Y luego llamar funciones de agregación sobre este objeto.
Las funciones de agregación tendrán efecto sobre las columnas que sea posible, es decir, si son funciones numéricas sólo tendrán efecto sobre los datos numéricos:

In [ ]:
by_empresa.mean()

In [ ]:
df.groupby('Empresa').mean()

Más ejemplos de funciones de agregación:

In [ ]:
by_empresa.std()

In [ ]:
df

In [ ]:
# En este caso la función min también tiene efecto sobre los datos textuales; se devuelve el menor valor de la cadena
# del nombre de las personas (ordenado lexicograficamente). Nótese que el valor de las ventas, no corresponde al de la persona,
# sino al valor menor de ventas de la empresa.

by_empresa.min()

In [ ]:
by_empresa.max()

In [ ]:
by_empresa.count()

In [ ]:
by_empresa.sum()

In [ ]:
# Podemos acceder a un solo valor:

by_empresa.sum().loc['FB']

In [ ]:
# Muchas veces no se crea un objeto groupby de forma explícita, sino que se utiliza directamente:

df.groupby('Empresa').sum().loc['FB']

In [ ]:
# El metodo describe es útil para presentar mucha información acerca del dataframe:

by_empresa.describe()

In [ ]:
by_empresa.describe().transpose()

In [ ]:
by_empresa.describe().transpose()['GOOG']






## Quiz

Modifique la función return_highest_sodium para retornar el nombre del cereal con más alto contenido en sodio.

La función recibe como argumento el dataframe con los cereales y retorna el string con el nombre de cereal requerido.

In [ ]:
df_cereals.head()

In [ ]:
def return_highest_sodium(df_cereals):
  """
  Parámetros:
     df_cereals: dataframe con las variables de los cereales

  Retorna:
     most_sodium_cereal: string con el nombre del cereal con mayor contenido de sodio
     less_sodium_cereal: string con el nombre del cereal con menor contenido de sodio
  """
  most_sodium = ""
  less_sodium = ""
  #Ponga su código acá
  most_sodium1 = df_cereals.sort_values
  most_sodium = most_sodium1.iloc[0]['Cereal Name']
  less_sodium1 = df_cereals.sort_values(by=['Sodium'])
  less_sodium = less_sodium1.iloc[-1]['Cereal Name']
  return most_sodium, less_sodium


def test_highest_sodium(df_cereals):
  try:
    res = return_highest_sodium(df_cereals)
  except:
    raise Exception("Error en la función")
  #Validar la respuesta
  if res != ("Shredded_Wheat_'n'Bran", 'Product_19'):
    raise Exception("Ese no es el cereal, revisa el código")
  return True

In [ ]:
#NO BORRAR ESTA LINEA
return_highest_sodium(df_cereals)

In [ ]:
#NO BORRAR ESTA LINEA
test_highest_sodium(df_cereals)

In [ ]:
#PRUEBE AQUI SU CÓDIGO
return_highest_sodium(df_cereals)

In [ ]:
#PRUEBE AQUI SU CÓDIGO
test_highest_sodium(df_cereals)

In [ ]:
df_cereals.sort_values?